name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.properties"
      - "**.java"
      - "**.toml"
      - "**.xml"
      - ".github/workflows/*.yml"
    branches:
      - "**"
  pull_request:
    branches:
      - master
jobs:
  fullbuild:
    runs-on: ubuntu-latest

    name: Java 20 build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: JDK Setup
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 20

      - name: D-BUS AT-SPI Installation
        run: sudo apt-get -y install at-spi2-core

      - name: Build
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: |
            build
            -PskipSpotless
        continue-on-error: true

      - name: Test
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: ./gradlew jacocoTestReport -PskipSpotless
        continue-on-error: true

      - name: Prepare Email Content
        run: |
            echo "BUILD_STATUS=${{ steps.build.outcome }}" >> $GITHUB_ENV
            echo "TEST_STATUS=${{ steps.test.outcome }}" >> $GITHUB_ENV



      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
              server_address: smtp.office365.com
              server_port: 587
              secure: false  # Use STARTTLS, which starts unsecured and then switches to a secure connection
              username: ${{ secrets.OUTLOOK_USERNAME }}
              password: ${{ secrets.OUTLOOK_PASSWORD }}
              subject: Build and Test Results for ${{ github.repository }}
              to: collegeforpete@gmail.com
              from: "LitiEngine Team 2 <${{ secrets.OUTLOOK_USERNAME }}>"
              body: |
                Build Status: ${{ env.BUILD_STATUS }}
                Test Status: ${{ env.TEST_STATUS }}
        continue-on-error: true


      - name: Package Creation
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: jpackage

            # - name: Static Analysis
            #   uses: gradle/gradle-build-action@v2.9.0
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #   if: ${{!github.event.pull_request.head.repo.fork}}
            #   with:
            #     arguments: |
          #       sonar
          #       -PskipSpotless


      - name: Code Style Validation
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: spotlessCheck
