name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.properties"
      - "**.java"
      - "**.toml"
      - "**.xml"
      - ".github/workflows/*.yml"
    branches:
      - "**"
  pull_request:
    branches:
      - master
jobs:
  fullbuild:
    runs-on: ubuntu-latest

    name: Java 20 build
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: JDK Setup
        uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 20

      - name: D-BUS AT-SPI Installation
        run: sudo apt-get -y install at-spi2-core

      - name: Build
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: |
            build

            -PskipSpotless

      - name: Test
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: ./gradlew jacocoTestReport -PskipSpotless

      - name: Zip Test Reports
        run: |
            zip -j litiengine-test-report.zip litiengine/build/reports/tests/test/index.html
            zip -j utiliti-test-report.zip utiliti/build/reports/tests/test/index.html

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
              server_address: smtp.office365.com
              server_port: 587
              secure: false  # Use STARTTLS, which starts unsecured and then switches to a secure connection
              username: ${{ secrets.OUTLOOK_USERNAME }}
              password: ${{ secrets.OUTLOOK_PASSWORD }}
              subject: LITIengine Build Test Report
              to: collegeforpete@gmail.com
              from: "Your Name <${{ secrets.OUTLOOK_USERNAME }}>"
              body: The build and test job for ${{ github.repository }} completed successfully.
              attachments: litiengine-test-reports.zip,utiliti-test-reports.zip

      - name: Package Creation
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: jpackage

            # - name: Static Analysis
            #   uses: gradle/gradle-build-action@v2.9.0
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #   if: ${{!github.event.pull_request.head.repo.fork}}
            #   with:
            #     arguments: |
          #       sonar
          #       -PskipSpotless


      - name: Code Style Validation
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: spotlessCheck
